### ISSUE TITLE
[DEPR]: frontend-app-library-authoring

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx-unsupported/frontend-app-library-authoring#439]
### Proposal Date

2024-06-10

### Target Ticket Acceptance Date

2024-06-24

### Earliest Open edX Named Release Without This Functionality

Sumac (2024-12)

### Rationale

`frontend-app-library-authoring` is a minimal frontend app for editing "v2" content libraries. It was never included by default in any Open edX release, and was only usable on instances that specifically installed it and its related plugins. The entire UI for editing content libraries is being re-imagined as part of the [Content Libraries Relaunch](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/4009426948/Libraries+Relaunch+MVP+Requirements) project, and a complete replacement UI with far more functionality is being developed in the Course Authoring MFE.

### Removal

The entire Library Authoring MFE (frontend app) will become unsupported with the Sumac release.

### Replacement

The Course Authoring MFE will be able to edit Courses, Libraries, and Taxonomies in one cohesive "Studio" experience. You can track this work on the [Libraries Relaunch board](https://github.com/orgs/openedx/projects/66/views/1).

### Migration

When upgrading to Sumac, simply uninstall the Library Authoring MFE and any associated plugins. For most users, this is not necessary as it's not installed by default.

**Comment by kdmccormick** [comment]
Marking this as Communicated since you posted it to https://discuss.openedx.org/t/deprecation-removal-library-authoring-mfe-frontend-app-library-authoring-439/13187

**Comment by bradenmacdonald** [comment]
@connorhaugh I do like that idea. I'm not sure how much of an effort it would be. It would require corresponding changes to `edx-platform` and `tutor-mfe`. I'm not planning to take on that rename at this time, but I'm supportive of it.

**Comment by bradenmacdonald** [comment]
Thanks for fixing that @kdmccormick ; I didn't realize moving this ticket on one board would affect it on the other.

**Comment by kdmccormick** [comment]
@bradenmacdonald Is it safe for me to archive the repo, or would you rather keep it writeable until it's been ported into frontend-app-course-authoring?

**Comment by kdmccormick** [comment]
I went ahead and archived this because even in the past 24 hours this repo has been causing confusion. If folks need to make temporary changes to this for development/prototyping reasons they should be able to fork it.
